test_blog/blog/urls.py
from django.urls import path
from blog import views

app_name = "blog"

urlpatterns = [
    path("about/", views.AboutView.as_view(), name="about"),
    path("", views.PostListView.as_view(), name="post_list"),
    path("post/<int:pk>", views.PostDetailView.as_view(), name="post_detail"),
    path("post/new/", views.CreatePostView.as_view(), name="post_new"),
    path("post/<int:pk>/edit", views.PostUpdateView.as_view(), name="post_edit"),
    path("post/<int:pk>/delete", views.PostDeleteView.as_view(), name="post_delete"),
    path("drafts/", views.DraftListView.as_view(), name="post_draft_list"),
    path("post/<int:pk>/comment/", views.add_comment_to_post, name="add_comment_to_post"),
    path("comment/<int:pk>/approve/", views.comment_approve, name="comment_approve"),
    path("comment/<int:pk>/delete/", views.comment_delete, name="comment_delete"),
    path("post/<int:pk>/publish/", views.post_publish, name="post_publish"),

    ]

test_blog/test_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls", namespace="blog")),
    path("accounts/login/", views.LoginView.as_view(), name="login"),
    path("accounts/logout/", views.LogoutView.as_view(), name="logout", kwargs={"next_page": "/"}),

]

test_blog/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.SET_DEFAULT, default=1)
    title = models.CharField(max_length=100)
    text = models.TextField()
    creation_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey("blog.Post",
                             related_name="comments",
                             on_delete=models.CASCADE)
    author = models.CharField(max_length=50)
    text = models.TextField(max_length=1000)
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("blog:post_list")

test_blog/blog/forms.py
from django import forms
from blog.models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ("author", "title", "text")

        widgets = {
            "title": forms.TextInput(attrs={"class": "textinputclass"}),
            "text": forms.Textarea(attrs={"class": "editable medium-editor-textarea postcontent"})
        }


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ("author", "text")

        widgets = {
            "author": forms.TextInput(attrs={"class": "textinputclass"}),
            "text": forms.Textarea(attrs={"class": "editable medium-editor-textarea"})

        }

test_blog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy


class AboutView(TemplateView):
    template_name = "about.html"


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by("-published_date")


class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = "/login/"
    redirect_field_name = "blog/post_detail/"
    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = "/login/"
    redirect_field_name = "blog/post_detail/"
    form_class = PostForm
    model = Post


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blog:post_list")


class DraftListView(LoginRequiredMixin, ListView):
    login_url = "login/"
    redirect_field_name = "blog/post_list"
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by("creation_date")

####

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect("blog:post_detail", pk=pk)


def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect("blog:post_detail", pk=post.pk)
    else:
        form = CommentForm(initial={"author": request.user.username})
    return render(request, "blog/comment_form.html", {"form": form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect("blog:post_detail", pk=comment.post.pk)

@login_required
def comment_delete(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect("blog:post_detail", pk=post_pk)

test_blog/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}

<p>Ahoj!</p>
<p>Toto se zku&scaron;ebn&iacute; blog z Udemy kurzu postaven&yacute; na Djangu.</p>
<p>Django is really strong and nic to work with.</p>

{% endblock %}

test_blog/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
          type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Exo+2:300i,400,600&display=swap&subset=latin-ext" rel="stylesheet">
    <script src="https://kit.fontawesome.com/2c77597766.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark techfont custom-navbar">
    <div class="container">
        <ul class="navbar-nav">
            <li class="nav-item active"><a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">Django Blog</a> </li>
            <li><a class="nav-link" href="{% url 'blog:about' %}">About blog</a> </li>
            <li><a class="nav-link" target="_blank" href="http://pancocha.eu">About me</a> </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'blog:post_new' %}">New Post</a> </li>
            <li><a class="nav-link" href="{% url 'blog:post_draft_list' %}">Drafts</a> </li>
            <li><a class="nav-link" href="{% url 'logout' %}"> <i class="fa fa-sign-out-alt"></i> Logout </a> </li>
            <li>{{user.username}}</li>
                {% else %}
                <li><a class="nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Login</a> </li>
            {% endif %}
        </ul>

    </div>
</nav>
<div class="content container">
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

test_blog/blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-primary">Post Comment</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

test_blog/blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
  <form action="" method="post">
      {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input class='btn btn-danger' type="submit" value="Confirm" />
  </form>
{% endblock %}

test_blog/blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}

<h1 class="posttitle">{{ post.title }}</h1>
{% if post.published_date %}
    <div class="date postdate">
        {{ post.published_date|date:"D, d M, Y" }}
    </div>
{% else %}
    <a class="btn btn-primary" href="{% url 'blog:post_publish' pk=post.pk %}" role="button">Publish</a>
{% endif %}


    {% if user.is_staff %}
        <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}" role="button">
            <i class="fas fa-edit"></i> Edit</a>
        <a class="btn btn-primary" href="{% url 'blog:post_delete' pk=post.pk %}" role="button">
            <i class="fas fa-trash-alt"></i> Delete</a>

    {% endif %}

<div class="container postcontent">
    <p class="postcontent">{{ post.text|safe|linebreaks }}</p>
</div>

<div class="container comments">
    <a class="btn btn-primary" href="{% url 'blog:add_comment_to_post' pk=post.pk %}" role="button">Add Comment</a>
    {% for comment in post.comments.all %}
         {% if user.is_authenticated or comment.approved_comment %}

              {{ comment.created_date }}
              {% if not comment.approved_comment %}
                  <a class="btn btn-primary" href="{% url 'blog:comment_delete' pk=comment.pk %}"><span class="fa fa-remove"></span></a>
                  <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="fa fa-check"></span></a>
              {% endif %}

          <p>{{ comment.text|safe|linebreaks }}</p>
          <p>Posted by: <strong>{{ comment.author }}</strong></p>

      {% endif %}
    {% empty %}
        <p>No comments posted.</p>
    {% endfor %}

</div>



{% endblock %}

test_blog/blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.creation_date|date:"D, d M, Y" }}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

test_blog/blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>New post</h1>

    <form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="Submit" class="save btn btn-default">Save - post form</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>

{% endblock %}

test_blog/blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% block content %}
<div class="centerstage">
    {% for post in post_list %}
        <div class="post">
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a> </h1>
            <div class="date">
                <p>Published on: {{ post.published_date|date:"D, d M, Y" }}</p>
            </div>
            <a href="{% url 'blog:post_detail' pk=post.pk %}#comments">Comments: {{ post.approved_comments.count }}</a>
        </div>
    {% endfor %}
</div>
{% endblock %}